### ISSUE TITLE
`_resetError` called too often, making it difficult to display errors

### ISSUE THREAD

**Issue by aliciusschroeder** [CR1337/rl-audio-player#1]
## Current Behavior
The `_resetError(_self)` method is currently called with almost every action, including `audioGetError`. This makes it basically impossible to ever display an error, as the error gets immediately resetted even when trying to retrieve it.

```c
AudioError * audioGetError(AudioObject *self) {
    _AudioObject *_self = (_AudioObject*)self;
    _resetError(_self);
    return _self->error; // <- This error attribute has just been set to 'no error' by _resetError
}
```

## Expected Behavior 
The `_resetError` method should only be called at appropriate times to clear the error, not with every single action or the occured error should be stored somewhere for future reference. This will allow errors to be properly retrieved and displayed when needed using `audioGetError` and `audioGetErrorString`.

## Possible Solution
Review all the places where `_resetError` is currently being called and remove it from actions where it doesn't make sense to immediately clear the error state. Only invoke it at key points where it's appropriate to reset errors. Another solution could be to store or log the occured errors somewhere.

**Comment by CR1337** [comment]
Thanks for pointing out. It should be fixed with [this](https://github.com/jlord/sheetsee.js/commit/a5c3785ed8d6a35868bc169f07e40e889087fd2e) commit. To retrieve an error call `audioGetError` immediately after the call of a potentially error causing function.
