### ISSUE TITLE
Potential resource leak in main.c

### ISSUE THREAD

**Issue by aliciusschroeder** [CR1337/rl-audio-player#12]
# Potential ressource leak in error handling of main.c

## Description
There is a potential ressource leak in the `main` function of `main.c`. The issue occurs in the error handling path when `fstat` fails after the file has been opened.

## Current Behavior
1. The file is opened on line 190 using `fopen`:
   ```c
   FILE *file = fopen(filename, "rb");
   ```

2. If the subsequent `fstat` call on line 203 (or any other EXIT_FAILURE returning check between opening and closing the file for that matter) fails, the function returns immediately:
   ```c
   if (fstat(fileDescriptor, &fileStats) == -1) {
       perror("fstat");
       return EXIT_FAILURE;
   }
   ```

3. In this error case, the file stream opened by `fopen` is never closed with `fclose`.

## Problem Details
- The opened file remains open when the program exits due to the `fstat` error
- This can lead to a resource leak, especially if the program is run multiple times or in a resource-constrained environment (like the Raspberry Pi this project is intended for)
- Over time, this could potentially exhaust the system's file descriptor limits

**Comment by CR1337** [comment]
`main.c` was never intended to be executed on the Raspberry Pi in production. Its purpose is to test the functionality implemented in `audio.h` and `audio.c`. Nevertheless it is good practice to free resources proactively instead of relying on the OS. Fixed with 9233f5836774153e486bd8b3b2bf8c9ac5c0f6d0
