### ISSUE TITLE
Duplicate Warning Display in `mainloop` Function of `main.c`

### ISSUE THREAD

**Issue by aliciusschroeder** [CR1337/rl-audio-player#14]
## Description
In the `mainloop` function of `main.c`, warning-level problems are currently being displayed twice, which may lead to redundant output and potential confusion for users.

## Current Behavior
1. Warnings are first displayed immediately after starting playback (lines 30-33):
```c
if (error->level == AUDIO_ERROR_LEVEL_WARNING) {
    const char *errorString = audioGetErrorString(error);
    fprintf(stderr, "Warning: %s\n", errorString);
}
```

2. The same warnings are displayed again at the end of each loop iteration (lines 91-94):
```c
if (error->level == AUDIO_ERROR_LEVEL_WARNING) {
    const char *errorString = audioGetErrorString(error);
    fprintf(stderr, "Warning: %s\n", errorString);
}
```

## Expected Behavior
Warnings should be displayed only once per occurrence, either at the beginning of playback or at the end of each loop iteration, but not both.

## Proposed Solution
To fix this issue, we should choose only one location to display warnings and remove the other one

**Comment by CR1337** [comment]
Thank you for pointing that out. I chose one location to display warning. Fixed with 9233f5836774153e486bd8b3b2bf8c9ac5c0f6d0
