### ISSUE TITLE
Unreachable Cleanup Operations in `mainloop` Function

### ISSUE THREAD

**Issue by aliciusschroeder** [CR1337/rl-audio-player#15]
## Description

There is unreachable code in the `mainloop` function of the audio player. The `audioDestroy(audio)` call on line 97 and `pthread_barrier_destroy(&barrier)` on line 98 are placed after a loop that can only be exited by a `return` statement, making these cleanup operations unreachable. This may lead to the `audio` object not being properly destroyed before the program exits and exposes a ressource leak risk.

## Current Behavior

1. The `mainloop` function contains a `while (true)` loop that handles user input.
2. The only way to exit this loop is through the 'q' case, which immediately returns from the function.
3. The cleanup operations (lines 97-98) are placed after the loop, making them unreachable.

## Expected Behavior

All code within the function should be reachable, especially important cleanup operations like destroying objects and freeing resources.

## Implications

This unreachable code may lead to resource leaks, as the `audio` object and the `pthread_barrier` are not being properly destroyed before the program exits.

**Comment by CR1337** [comment]
I pulled the cleanup operations into the case where the function returns. Fixed with 9233f5836774153e486bd8b3b2bf8c9ac5c0f6d0
