### ISSUE TITLE
Add default case to main switch statement in the `mainloop` function for better user experience

### ISSUE THREAD

**Issue by aliciusschroeder** [CR1337/rl-audio-player#18]
## Description

In the `mainloop` function, there's a switch statement that handles user input commands. Currently, this switch statement lacks a default case.

## Current Behavior

When a user inputs an unrecognized command, the program silently ignores it without providing any feedback. This might confuse users, especially those unfamiliar with the available commands.

## Expected Behavior

The switch statement should include a default case that informs the user when they've entered an invalid or unrecognized command. This would provide immediate feedback and guide users towards using the correct commands.

## Proposed Solution

Add a default case to the switch statement that prints a message indicating the command was not recognized and suggests using the 'h' command for help. For example:

```c
default:
    printf("Unrecognized command. Type 'h' for help.\n");
    break;
```

## Impact

This change will improve the user experience by:
1. Providing immediate feedback for incorrect inputs
2. Guiding users towards the help command when they're unsure
3. Reducing potential confusion caused by silently ignored inputs

**Comment by CR1337** [comment]
Good idea. Even though `main.c` is only there for testing purposes this addition will increase user experience while testing manually. Fixed with 9233f5836774153e486bd8b3b2bf8c9ac5c0f6d0
