### ISSUE TITLE
Audio doesn't work under Windows Subsystem for Linux (WSL) without .asoundrc changes

### ISSUE THREAD

**Issue by aliciusschroeder** [CR1337/rl-audio-player#2]
## Problem
When attempting to run the `rl-audio-player` example program under a recent Windows Subsystem for Linux (WSL) environment, the audio playback doesn't work out of the box. You encounter the following error:

```
Reading file.
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5204:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5204:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1342:(snd_func_refer) error evaluating name
ALSA lib conf.c:5204:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5727:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2721:(snd_pcm_open_noupdate) Unknown PCM default
Total duration: 60.00 seconds
Segmentation fault
```

## Workaround
To get audio working, you need to install the alsa-pulse-plugin and update the ALSA configuration in the `~/.asoundrc` file to use the PulseAudio compatible WSL backend.

Install ALSA plugins:
```
sudo apt install libasound2-plugins
```

Add the following lines to your `~/.asoundrc` file:

```
pcm.!default { type pulse fallback "sysdefault" }
ctl.!default { type pulse } 
```

This configures ALSA to connect to a PulseAudio server as the default device. The PulseAudio WSL daemon acts as a bridge to transmit audio from the WSL environment to the Windows host.

After applying this configuration change, audio should work when running the `rl-audio-player` example program.

## Additional Context
WSL doesn't have direct access to Windows audio devices. Instead, it relies on an audio transport service like PulseAudio to send audio from the Linux environment to Windows for playback.

Microsoft provides a [PulseAudio server](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps#install-support-for-audio-and-opengl) that works seamlessly with WSL. Many Linux GUI apps rely on this PulseAudio transport for audio support under WSL.

The `~/.asoundrc` configuration change tells ALSA to use this PulseAudio server by default, instead of trying to directly access an audio device (which fails in the WSL context).

## Suggested Improvement
It might be helpful to document this necessary WSL-specific workaround in the README, so that developers using WSL can quickly get the program running. 

I can open a separate PR to add a "Windows Subsystem for Linux (WSL)" section to the README that explains the `~/.asoundrc` change, but I wanted to start with an issue to see if you would find that documentation valuable first. 

Even if not, I'm happy for any developer who is developing on this project under WSL who finds this Issue helpful and can save themselves all the hassle I had.

**Comment by CR1337** [comment]
Thank you for your contribution and research. The target system for this software is a Raspberry Pi where this workaround is not necessary. However espsecially for developers working on windows machines this can be a huge relief. So feel free to open a PR.

**Comment by aliciusschroeder** [comment]
done :)
