### ISSUE TITLE
Incorrect Total Duration Display for some Stereo Audio Files

### ISSUE THREAD

**Issue by aliciusschroeder** [CR1337/rl-audio-player#4]
The audio player incorrectly displays the total duration for some audio files with 2 channels (stereo). The issue seems to depend on the sample rate and total duration of the audio file.

Here's a table showing the actual total duration and the displayed total duration for various audio files:

| Channels | Sample Rate (Hz) | Actual Total Duration (s) | Displayed Total Duration (s) |
|----------|------------------|---------------------|----------------------------|
| 1        | 44100            | 32                  | 32                         |
| 2        | 8000             | 16                  | 16                         |
| 2        | 44100            | 32                  | **7.65** ⚠️ |
| 2        | 8000             | 32                  | 32                         |
| 2        | 44100            | 16                  | 16                         |
| 2        | 44100            | 64                  | **15.30** ⚠️ |

As highlighted in the table, when the audio file has 2 channels and a sample rate of 44100 Hz, the displayed total length is significantly shorter than the actual duration. However, for stereo files with a sample rate of 8000 Hz, the total length is displayed correctly. An excemption seems to be the just 16 seconds long audio file with 44100 Hz.

To reproduce the test files, the following command was used:
```
sox -n -R -r [sample rate] -b 16 -c [channels] [file name] synth [duration] whitenoise
```

**Comment by CR1337** [comment]
I will have a look at this and also #3. I suspect they have the same underlying issue. Having access to the audio files that lead to these results would be helpful. Maybe you can provide them somehow.

**Comment by CR1337** [comment]
I might have found the problem. It was an integer overflow in some variables representing millisecond timestamps. I changed the variables bit widths to 64 with [this](https://github.com/CR1337/rl-audio-player/commit/933c5eeeb868ef7a527b842e661fffee3ab4971c) commit. Please have a look if it work for you now.

**Comment by aliciusschroeder** [comment]
Thanks for the fast reaction. I can confirm that your recent commit indeed fixes this issue and all total play times are correctly displayed now. Upon taking a further look I think the only place that was prone to an overflow problem was actually this calculation due to the left-to-right integer arithmetic in C:
```c
_self->riffData.audioLength = _self->riffData.dataSize 
        * MICROSECONDS_PER_MILLISECOND 
        / _self->riffData.byteRate;
```
In my local tests changing only this line to:
```c
_self->riffData.audioLength = (_self->riffData.dataSize 
        / _self->riffData.byteRate) 
        * MICROSECONDS_PER_MILLISECOND;
```
fixes all problems related to incorrectly displayed total play times so unless you have plans on supporting audio files larger than  4 GB changing this calculation would allow you to return to 32-bit variables.

However I'm afraid to say that the recent switch to 64-bit width did not solve #3 which still occurs in exactly the same way as before.

Regarding your question in https://github.com/CR1337/rl-audio-player/issues/4#issuecomment-2106199467 if generarting the test files locally is not possible for you I can find a way to share the files I've used, otherwise you should be able to reproduce the audio files that lead to these results with the command I provided in my first comment like this:
```
sox -n -R -r 44100 -b 16 -c 1 audio_44100Hz_1ch_32s.wav synth 32 whitenoise
sox -n -R -r 8000 -b 16 -c 2 audio_8000Hz_2ch_16s.wav synth 16 whitenoise
sox -n -R -r 44100 -b 16 -c 2 audio_44100Hz_2ch_32s.wav synth 32 whitenoise
sox -n -R -r 8000 -b 16 -c 2 audio_8000Hz_2ch_32s.wav synth 32 whitenoise
sox -n -R -r 44100 -b 16 -c 2 audio_44100Hz_2ch_16s.wav synth 16 whitenoise
sox -n -R -r 44100 -b 16 -c 2 audio_44100Hz_2ch_64s.wav synth 64 whitenoise
```

**Comment by CR1337** [comment]
As the increase of used memory due to the increased bit witdh of timestamps doesn't really matter on modern hardware I decided to stay with the 64 bit width. 
In case a user wants to play music using a 7.1 sound system, 32 bit timestamps would only allow for about 90 minutes of playback time given a bit depth of 16 and a sample rate of 44.1 kHz. I think here enabling more artistic freedom is more valuable than saving a hand full of bytes.

Regarding #3 there indeed was another issue. It should be fixed with [this](https://github.com/CR1337/rl-audio-player/commit/83d36f9d3e55f4f23b61c9889eb3f01f6ee17944) commit.

**Comment by CR1337** [comment]
In case you are interested in playing around with different sample rates, bit depths and channel amounts to see how large the file would get, I can recommend this tool:

https://www.colincrawley.com/audio-file-size-calculator/

**Comment by aliciusschroeder** [comment]
Thanks for providing the fast fix for both issues and recommending the tool - it's pretty handy indeed.

I agree that users of 7.1 sound systems playing more than 90 minutes of playback on a Raspberry Pi shouldn't feel left out - although they probably would anyway, since the FMT chunk size is currently hard-coded to 16 bytes, and surround wav files are usually encoded with a 40-byte FMT chunk.

This seems to apply to most non-mono/stereo files btw as even a simple 2.1 configuration tends to use the WAVE_FORMAT_EXTENSIBLE format code leading to an error when loading the file. I.e.:
```sox -n -R -r 44100 -b 16 -c 3 audio_44100Hz_3ch_32s.wav synth 32 whitenoise```

I didn't open an issue on that topic yet, because I wasn't sure if this might be out-of-scope for this project but I think this should either be mentioned as a limitation or be fixed.

**Comment by CR1337** [comment]
> I didn't open an issue on that topic yet, because I wasn't sure if this might be out-of-scope for this project but I think this should either be mentioned as a limitation or be fixed.

Well now it is in-scope. See #10

**Comment by CR1337** [comment]
#10 is now merged.
